<?php

namespace ScrapyardIO\Sensors\Distance\VL53L0X\Enums;

enum VL53L0XCommand: int
{
    // System Control Registers
    case SYSRANGE_START = 0x00;
    case SYSTEM_SEQUENCE_CONFIG = 0x01;
    case SYSTEM_INTERMEASUREMENT_PERIOD = 0x04;
    case SYSTEM_RANGE_CONFIG = 0x09;
    case SYSTEM_INTERRUPT_CONFIG_GPIO = 0x0A;
    case SYSTEM_INTERRUPT_CLEAR = 0x0B;
    case SYSTEM_THRESH_HIGH = 0x0C;
    case SYSTEM_THRESH_LOW = 0x0E;

    // Result Registers
    case RESULT_INTERRUPT_STATUS = 0x13;
    case RESULT_RANGE_STATUS = 0x14;

    // Crosstalk & Algorithm Registers
    case CROSSTALK_COMPENSATION_PEAK_RATE_MCPS = 0x20;
    case PRE_RANGE_CONFIG_MIN_SNR = 0x27;
    case ALGO_PART_TO_PART_RANGE_OFFSET_MM = 0x28;
    case ALGO_PHASECAL_LIM = 0x30;
    case GLOBAL_CONFIG_VCSEL_WIDTH = 0x32;
    case HISTOGRAM_CONFIG_INITIAL_PHASE_SELECT = 0x33;

    // Final Range Configuration
    case FINAL_RANGE_CONFIG_MIN_COUNT_RATE_RTN_LIMIT = 0x44;
    case MSRC_CONFIG_TIMEOUT_MACROP = 0x46;
    case FINAL_RANGE_CONFIG_VALID_PHASE_LOW = 0x47;
    case FINAL_RANGE_CONFIG_VALID_PHASE_HIGH = 0x48;

    // Dynamic SPAD Registers
    case DYNAMIC_SPAD_NUM_REQUESTED_REF_SPAD = 0x4E;
    case DYNAMIC_SPAD_REF_EN_START_OFFSET = 0x4F;

    // Pre-Range Configuration
    case PRE_RANGE_CONFIG_VCSEL_PERIOD = 0x50;
    case PRE_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x51;
    case PRE_RANGE_CONFIG_TIMEOUT_MACROP_LO = 0x52;
    case HISTOGRAM_CONFIG_READOUT_CTRL = 0x55;
    case PRE_RANGE_CONFIG_VALID_PHASE_LOW = 0x56;
    case PRE_RANGE_CONFIG_VALID_PHASE_HIGH = 0x57;

    // MSRC & Check Limit Registers
    case MSRC_CONFIG_CONTROL = 0x60;
    case PRE_RANGE_CONFIG_SIGMA_THRESH_HI = 0x61;
    case PRE_RANGE_CONFIG_SIGMA_THRESH_LO = 0x62;
    case PRE_RANGE_MIN_COUNT_RATE_RTN_LIMIT = 0x64;
    case FINAL_RANGE_CONFIG_MIN_SNR = 0x67;

    // Final Range Timing
    case FINAL_RANGE_CONFIG_VCSEL_PERIOD = 0x70;
    case FINAL_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x71;
    case FINAL_RANGE_CONFIG_TIMEOUT_MACROP_LO = 0x72;

    // Power Management & GPIO
    case POWER_MANAGEMENT_GO1_POWER_FORCE = 0x80;
    case SYSTEM_HISTOGRAM_BIN = 0x81;
    case GPIO_HV_MUX_ACTIVE_HIGH = 0x84;
    case I2C_MODE_CONTROL = 0x88;
    case VHV_CONFIG_PAD_SCL_SDA__EXTSUP_HV = 0x89;
    case I2C_SLAVE_DEVICE_ADDRESS = 0x8A;

    // Global SPAD Configuration
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_0 = 0xB0;
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_1 = 0xB1;
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_2 = 0xB2;
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_3 = 0xB3;
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_4 = 0xB4;
    case GLOBAL_CONFIG_SPAD_ENABLES_REF_5 = 0xB5;
    case GLOBAL_CONFIG_REF_EN_START_SELECT = 0xB6;

    // Identification & Reset
    case SOFT_RESET_GO2_SOFT_RESET_N = 0xBF;
    case IDENTIFICATION_MODEL_ID = 0xC0;
    case IDENTIFICATION_REVISION_ID = 0xC2;

    // Core Result Registers (Page 1)
    case RESULT_CORE_AMBIENT_WINDOW_EVENTS_RTN = 0xBC;
    case RESULT_CORE_AMBIENT_WINDOW_EVENTS_REF = 0xD0;
    case RESULT_CORE_RANGING_TOTAL_EVENTS_REF = 0xD4;

    // Calibration
    case OSC_CALIBRATE_VAL = 0xF8;
    
    // Page Select Control
    case PAGE_SELECT = 0xFF;
}
